version: '3.8'

services:

    db:
        image: mariadb
        container_name: ${APP_NAME}-mysql
        restart: always
        volumes:
            - ./database:/var/lib/mysql:delegated
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}

    wordpress:
        image: wordpress:6.0.2-fpm-alpine
        container_name: ${APP_NAME}-wordpress
        restart: unless-stopped
        depends_on:
            - db
        volumes:
            - ../wordpress:/var/www/html
        environment:
            - WORDPRESS_DB_HOST=db
            - WORDPRESS_DB_USER=${DB_USER}
            - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
            - WORDPRESS_DB_NAME=${DB_NAME}
        env_file: .env

    webserver:
        image: nginx:latest
        container_name: ${APP_NAME}-webserver
        restart: unless-stopped
        depends_on:
            - wordpress
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../wordpress:/var/www/html
            - ./nginx/:/etc/nginx/conf.d
            - ./certs:/etc/certs

    # Redis container
    # Uncomment for installing Redis container
    # redis:
    #     image: arm64v8/redis:latest
    #     container_name: ${APP_NAME}-redis
    #     environment:
    #         - ALLOW_EMPTY_PASSWORD=yes
    #     ports:
    #         - '6379:6379'
    #     volumes:
    #         - ./redis_database:/bitnami/redis/data

volumes:
    wordpress:
    database: