version: '3.9'

services:

    wp:
        image: wordpress:latest
        ports:
            - "80:80"
        volumes:
            - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
            - ../wp-app:/var/www/html
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: ${DB_NAME}
            WORDPRESS_DB_USER: ${DB_USER}
            WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
        depends_on:
            - db
        links:
            - db

    db:
        image: mariadb
        container_name: ${APP_NAME}-mysql
        ports:
            - "3306:3306"
        volumes:
            - ./database:/var/lib/mysql:delegated
        environment:
            - MYSQL_DATABASE=${DB_NAME}
            - MYSQL_USER=${DB_USER}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        restart: always

    wpcli:
        container_name: ${APP_NAME}-wpcli
        build:
            context: .
            dockerfile: ./config/dockerfile/php.dockerfile
        volumes:
            - ../frankwatching-6.0/www:/var/www/html/public
        links:
            - mysql:db
        depends_on:
            - wp
            - db
        working_dir: /var/www/html/public
        entrypoint: ['wp', '--allow-root']

    # Redis container
    # Uncomment for installing Redis container
    # redis:
    #     image: arm64v8/redis:latest
    #     container_name: ${APP_NAME}-redis
    #     environment:
    #         - ALLOW_EMPTY_PASSWORD=yes
    #     ports:
    #         - '6379:6379'
    #     volumes:
    #         - ./redis_database:/bitnami/redis/data